name: Continuous Integration - Reusable
on: [workflow_call]
jobs:
  CI_Steps:
    runs_on: [self-hosted]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Code Lint
        run: echo Ok
      - name: Install NodeJS modules
        run: npm install
      - name: Code Unit Tests
        run: echo OK
      - name: Code Integration Tests
        run: echo OK
      - name: Code Review
        run: echo OK
      - name: Release Software
        run: echo OK